<a href="https://colab.research.google.com/github/shahnawazsyed/MAT422/blob/main/graph_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **4.2 Graph and Graph Modeling**

In [34]:
import numpy as np
from scipy.linalg import eigh

Any graph consists of a set of objects, called nodes, connected by edges. Mathematically, we define this as G(V,E), where V is the set of nodes, and E the set of edges.

The degree of a node in a graph is the number of edges connected to the node. In-degree counts the edges towards the node, and out-degree counts those leaving the node.

A graph with *n* nodes can be represented by a *n* by *n* matrix. A value of 1 at row *i*, column *j* indicates a connection between nodes $v_i$ and $v_j$

In [35]:
graph = np.array([[0,1,0,0,1],
                [1,0,1,1,0],
                [0,1,0,1,0],
                [0,1,1,0,1],
                [1,0,0,1,0]]) #a 5 node graph, 0 indexed by node

print(graph[0,1]) #node 0 is connected to node 1
print(graph[1,4]) #node 1 is not connected to node 4

1
0


The degree matrix D is a diagonal matrix where each entre D[i,i] is the degree of node $v_i$.

In [36]:
D = np.diag(np.sum(graph, axis=0))
print(D)

[[2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 2]]


A Laplacian matrix is constructed by subtracted the adjacency matrix from the degree matrix

In [37]:
L = D - graph
print(L)

[[ 2 -1  0  0 -1]
 [-1  3 -1 -1  0]
 [ 0 -1  2 -1  0]
 [ 0 -1 -1  3 -1]
 [-1  0  0 -1  2]]


The second smallest eigenvalue of L indicates the algebraic connectivity of the graph, or how well-connected it is.

In [38]:
eigenvalues, eigenvectors = eigh(L)
eigenvalues.sort()
print(eigenvalues[1]) #algebraic connectivity

1.3819660112501087


The number of connected nodes in the graph is shown by the number of eigenvalues equal to zero.

In [39]:
num_connected_components = np.sum(eigenvalues < 1e-5)
print(num_connected_components)

1


Graph partitioning is a method that divides a graph into subgraphs. This is useful for clustering. The aim is to separate the graph into subgraphs which are as disconnected as possible, while balancing the number of nodes/edges in each part.

We start by obtaining the eigenvector corresponding to the second smallest eigenvalue of the Laplacian matrix:

In [40]:
vector = eigenvectors[:,1]
print(vector)

[-0.51166727  0.19543951  0.63245553  0.19543951 -0.51166727]


We partition the vector into positive and negative sides:

In [41]:
partition_1 = [value for i, value in enumerate(vector) if value >= 0]
partition_2 = [value for i, value in enumerate(vector) if value < 0]
print("pos: ", partition_1)
print("neg: ", partition_2)

pos:  [0.19543950758485523, 0.632455532033676, 0.19543950758485573]
neg:  [-0.5116672736016928, -0.511667273601692]
