<a href="https://colab.research.google.com/github/shahnawazsyed/MAT422/blob/main/HW13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.3 Linear Regression**


*   QR Decomposition
*   Least-squares decomposition
*   Linear Regression


---



In [1]:
import numpy as np

# **1.3.1 QR Decomposition**





QR Decomposition utilizes the result of the gram-schmidt process,

In [ ]:
A = np.array([[12, 2, -3],
              [3, 9, 2],
              [10, -5, 0]])
Q, R = np.linalg.qr(A)
print("Q: ", Q)
print("R: ", R)
# need to add much more

Q:  [[-0.75443354 -0.18617351 -0.62941994]
 [-0.18860838 -0.85700114  0.47955805]
 [-0.62869461  0.48050855  0.61143652]]
R:  [[-15.90597372  -0.06286946   1.88608384]
 [  0.         -10.48790005  -1.15548175]
 [  0.           0.           2.84737593]]


# **1.3.2 Least-squares problems**



Let A ∈ R<sup>*n*x*m*</sup> and b ∈ R<sup>*n*</sup>. In trying to solve the system Ax=b, we find that the system is inconsistent. If A is a square matrix (*n* = *m*), we can use A<sup>-1</sup> to solve the system. However, in cases where A is not a square matrix, we cannot use A<sup>-1</sup>, thus we approximate the solution $\hat{x}$, such that:

dist(b,A$\hat{x}$) ≤ dist(b,Ax) for all other vectors x in R<sup>*n*</sup>

Where dist(v,w) = ||v-w|| is the distance between vectors v and w.

We can derive a solution for the least-squares problem where:

In [41]:
A = np.random.random((3, 2))
b = np.random.random((3, 1))
print("A: ", A)
print("b: ", b)

A:  [[0.99760001 0.86319897]
 [0.87973183 0.52044314]
 [0.15975445 0.75834877]]
b:  [[0.31732097]
 [0.83509295]
 [0.55138684]]


In [42]:
squaredA = np.matmul(np.transpose(A),A) #create a square matrix from A
print(squaredA)

[[1.79465536 1.44012729]
 [1.44012729 1.59106639]]


In [43]:
Atb = np.matmul(np.transpose(A), b) #compute transpose of A times B
print(Atb)

[[1.13930375]
 [1.12667306]]


In [44]:
#We can now solve Ax=b, as we have a square matrix A (squaredA)
x = np.linalg.solve(squaredA, Atb)
print("Least squares solution:")
print(x)

Least squares solution:
[[0.24333671]
 [0.4878723 ]]


We can determine the precision of our estimation by calculating its residual. A smaller residual is always better.

In [50]:
def residual(a, x, b):
  return b - A @ x
print("Residual: ", np.linalg.norm(residual(A, x, b)))

Residual:  0.5245886655828828


For the projection A*x* to be the best estimation of b, we want the former to be the closest possible vector within the column space of A. Thus, the residual vector should be orthogonal to the column space of A.


In [52]:
def isOrthogonal(residual, A):
  for i in range(A.shape[1]):
    dot_product = np.dot(A[:, i], residual)
    if not np.isclose(dot_product, 0, atol=1e-10):
      return False
  return True
r = residual(A, x, b)
print("Orthogonality: ", isOrthogonal(r, A))

Orthogonality:  True


# **1.3.3 Linear Regression**